/**
  * Created by cris on 08/11/16.
  */
import java.nio.file.{Files, Paths}

import org.scalatest._
import org.junit.runner.RunWith

import scala.collection.mutable
//import org.scalatest.junit.JUnitRunner
import org.junit.Test
import org.junit.Assert.assertArrayEquals


 class TokenizerTest extends FunSuite {


  //create trait containing Strings to be used to test

    val string1="Los gatos negros son bonitos."
    val string2="Nadie podrá vivir eternamente"
    val string3="Los ingenieros informáticos son muy inteligentes"
    val string4="Aún no puedo creer que Trump haya ganado las elecciones."
    val string5="El cielo es azul. El agua es transparente y las amapolas son rojas."
    val string6="Los lobos aullaban desesperadamente"
    val string7="Dijo que lo esperáramos aquí mientras compraba galletas"
    val string8="Te advertimos que serían duros contigo"
    val string9="reconozco que me comporté mal"
    val string10="todo esfuerzo valdrá la pena"
    val string11="dejaron que murieran de hambre"
    val string12="nos atracaron a mano armada"
    val string13="cuando éramos niños cazábamos muchos bichos"
    val string14="con tanto calor se funde el hielo"
    val string15="El sedentarismo físico se presenta con mayor frecuencia en la vida moderna urbana, en sociedades altamente tecnificadas en donde todo está pensado para evitar grandes esfuerzos físicos, en las clases altas y en los círculos intelectuales en donde las personas se dedican más a actividades cerebrales."
   //needed paths
   val verbsPath="/home/cris/mrcrstnherediagmez@gmail.com/Spanish_Lematizer/data/es-verbs.txt"
   val tokenizer=new Tokenizer
   val tagger=new PosTagger
   val lemmatizer=new Lemmatizer(verbsPath)
  /**
    * Testing Tokenizer
    */

    //testing find tokens method
test("find tokens test"){
   tokenizer.find_tokens(string1)
  assert(tokenizer.find_tokens(string1)==List(List("Los","gatos","negros","son","bonitos",".")))
  assert(tokenizer.find_tokens(string2)==List(List("Nadie","podrá","vivir","eternamente")))
  assert(tokenizer.find_tokens(string3)==List(List("Los","ingenieros","informáticos","son","muy","inteligentes")))
  assert(tokenizer.find_tokens(string4)==List(List("Aún","no","puedo","creer","que","Trump","haya","ganado","las","elecciones",".")))
   assert(tokenizer.find_tokens(string5)==List(List("El","cielo","es","azul","."),List("El","agua","es","transparente","y","las","amapolas","son","rojas",".")))
   assert(tokenizer.find_tokens(string6)==List(List("Los","lobos","aullaban","desesperadamente")))
   assert(tokenizer.find_tokens(string7)==List(List("Dijo","que","lo","esperáramos","aquí","mientras","compraba","galletas")))
   assert(tokenizer.find_tokens(string8)==List(List("Te","advertimos","que","serían","duros","contigo")))
   assert(tokenizer.find_tokens(string9)==List(List("reconozco","que","me","comporté","mal")))
   assert(tokenizer.find_tokens(string10)==List(List("todo","esfuerzo","valdrá","la","pena")))
   assert(tokenizer.find_tokens(string11)==List(List("dejaron","que","murieran","de","hambre")))
   assert(tokenizer.find_tokens(string12)==List(List("nos","atracaron","a","mano","armada")))
   assert(tokenizer.find_tokens(string13)==List(List("cuando","éramos","niños","cazábamos","muchos","bichos")))
   assert(tokenizer.find_tokens(string14)==List(List("con","tanto","calor","se","funde","el","hielo")))
   assert(tokenizer.find_tokens(string15)==List(List("El","sedentarismo","físico","se","presenta","con","mayor","frecuencia","en","la","vida","moderna","urbana",",","en","sociedades","altamente","tecnificadas","en","donde","todo","está","pensado","para","evitar","grandes","esfuerzos","físicos",",","en","las","clases","altas","y","en","los","círculos","intelectuales","en","donde","las","personas","se","dedican","más","a","actividades","cerebrales","."
  )))
}
    test(" count sentences test"){
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string1))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string2))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string3))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string4))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string5))==2)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string6))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string7))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string8))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string9))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string10))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string11))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string12))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string13))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string14))==1)
       assert(tokenizer.count_sentences(tokenizer.find_tokens(string15))==1)
    }


    /**
      * Testing POSTagger
      */
test("parole to penntreebank tag test") {
     assert(tagger.parole2penntreebank("El", "DA")==("El","DT"))
     assert(tagger.parole2penntreebank("pájaro", "NC")==("pájaro","NN"))
     assert(tagger.parole2penntreebank("está", "VMI")==("está","VB"))
     assert(tagger.parole2penntreebank("en", "SP")==("en","IN"))
     assert(tagger.parole2penntreebank("la", "DA")==("la","DT"))
     assert(tagger.parole2penntreebank("jaula", "NC")==("jaula","NN"))
     assert(tagger.parole2penntreebank(".", "Fp")==(".","."))
   }

   test("pentreebank to universal test"){
     assert(tagger.penntreebank2universal("El","DT")==("El","DT"))
     assert(tagger.penntreebank2universal("pájaro","X")==("pájaro","X"))
     assert(tagger.parole2penntreebank("está", "VB")==("está","VB"))
     assert(tagger.parole2penntreebank("en", "IN")==("en","IN"))
     assert(tagger.parole2penntreebank("la", "DT")==("la","DT"))
     assert(tagger.parole2penntreebank("jaula", "NC")==("jaula","NN"))
     assert(tagger.parole2penntreebank(".", "Fp")==(".","."))
   }

   test("parole to universal"){
     assert(tagger.parole2universal("El", "DA")==("El","DT"))
     assert(tagger.penntreebank2universal("pájaro","NC")==("pájaro","X"))
     assert(tagger.parole2penntreebank("está", "VMI")==("está","VB"))
     assert(tagger.parole2penntreebank("en", "SP")==("en","IN"))
     assert(tagger.parole2penntreebank("la", "DA")==("la","DT"))
     assert(tagger.parole2penntreebank("jaula", "NC")==("jaula","NN"))
     assert(tagger.parole2penntreebank(".", "Fp")==(".","."))
   }

   /**
     * Testing Lemmatizer
     */

test("singularize"){
  var wordforms=List[List[String]]()
  var testDict=mutable.Map.empty[String,List[String]]
  //read file
  scala.io.Source.fromFile("../Spanish_Lematizer/test/data/wordforms-es-davies.csv").getLines().foreach(line => wordforms::=line.split(" ").toList)
  wordforms.reverse.foreach(l=> {
    val splitted=l(0).split(",").map(u=> u.tail.stripPrefix("\"").stripSuffix("\""))
    val w=splitted(0)
    val lemma=splitted(1)
    val tag=splitted(2)
    val f=splitted(3)

    if(tag=="n"){
      testDict += (lemma -> (w +: testDict.getOrElse(lemma, List.empty)))
    }
  })

  var i=0
  var n=0
  testDict.foreach(f=> {
    if(lemmatizer.singularize((f._2.sortWith(_.length<_.length)).head,"NN")==f._1) i=i+1
    n=n+1
  })

  assert(i.toFloat/n > 0.93)
}

   test("predicative"){
     var wordforms=List[List[String]]()
     var testDict=mutable.Map.empty[String,List[String]]
     //read file
     scala.io.Source.fromFile("../Spanish_Lematizer/test/data/wordforms-es-davies.csv").getLines().foreach(line => wordforms::=line.split(" ").toList)
     wordforms.reverse.foreach(l=> {
       val splitted=l(0).split(",").map(u=> u.tail.stripPrefix("\"").stripSuffix("\""))
       val w=splitted(0)
       val lemma=splitted(1)
       val tag=splitted(2)
       val f=splitted(3)

       if(tag=="j"){
         testDict += (lemma -> (w +: testDict.getOrElse(lemma, List.empty)))
       }
     })
     var i=0
     var n=0
     testDict.foreach(f=> {
       if(lemmatizer.predicative(f._2.sortWith(_.length<_.length).head)==f._1) i=i+1
       n=n+1
     })

     assert(i.toFloat/n > 0.92)
   }


test("find lemma") {
  var i = 0
  var n = 0
  var faults = List[(String, String)]()
  lemmatizer.mappedVerbs.foreach(u => {
    if (lemmatizer.find_lemma(u._1) == u._2) i = i + 1 else faults ::= u
    n = n + 1
  })


  var pyfaults = List(
    "bebierais", "consiento", "yazcáis", "compuesto", "fuera", "batiendo", "mandáis", "solierais", "constituyó", "eduquemos", "enamoréis", "sufríais",
    "pinte", "vistiendo", "constituyo", "sonreíais", "empecemos", "durmiera", "tropezéis", "extinguieron", "quisieras", "prometimos", "satisfagamos",
    "sonreías", "destruyera", "sonreían", "deshiciste", "oponemos", "compusiéramos", "yerran", "yerras", "advirtieras", "haría", "advirtieran",
    "permanecieras", "permanecieran", "reservéis", "deshicisteis", "derrita", "derrite", "derrito", "extienden", "mostremos", "metieran",
    "metieras", "medido", "ladré", "juegan", "acompañen", "acompañes", "juegas", "ladre", "prometa", "prometo", "reparé", "explote", "atrajéramos",
    "hay", "hirieron", "consumamos", "repara", "sucedáis", "bendijo", "respondamos", "bendije", "sufras", "sufran", "esquío", "desagraden",
    "esquíe", "esquía", "desagrades", "cerremos", "entreviste", "crezcáis", "huyeron", "vengamos", "bajen", "influí", "bajes", "satisficieron",
    "adorne", "vacían", "previste", "rijamos", "vacías", "sitúan", "oyeron", "comprendan", "sitúas", "felicites", "feliciten", "tiñan",
    "tiñas", "sonreísteis", "leímos", "jures", "maquilles", "cosiera", "maquillen", "mezcle", "juren", "constituyen", "constituyes", "asistieron",
    "desharía", "trates", "tienen", "tienes", "convenciéramos", "surges", "aborden", "predecíais", "abordes", "surgen", "requerido", "despidáis",
    "cogió", "guarden", "heríamos", "sobreviváis", "tomen", "formen", "vomite", "formes", "tomes", "moviste", "convino", "inmigremos", "convine",
    "cosierais", "sufría", "compitas", "convenido", "compitan", "saludes", "saluden", "devolvieran", "rompa", "rompo", "devolvieras", "barrimos",
    "pregunten", "enseñéis", "preguntes", "corriera", "busquemos", "supongas", "supongan", "prohíbes", "conviniste", "abusen", "abuses", "prohíben",
    "creas", "agüeras", "agüeran", "crean", "corrija", "corrijo", "uníamos", "causen", "comiéramos", "causes", "uniendo", "habrá", "pase", "llovieras",
    "llovieran", "imprima", "imprimo", "invadían", "cogiéramos", "comprendamos", "condenen", "condenes", "morí", "esquíen", "esquíes", "desaparezcáis",
    "tradujerais", "abandone", "cabrías", "cabrían", "corríamos", "contiene", "cubrió", "medimos", "apuestes", "apuesten", "conduzcas", "conduzcan",
    "tañendo", "cansen", "canses", "gruñía", "frito", "admire", "voy", "barristeis", "caíste", "admiré", "detengamos", "puesto", "creía", "tañeron",
    "respiréis", "intenten", "comáis", "prometan", "hagáis", "prometas", " aflijáis", "pierdo", "dueles", "apareciéramos", "escrito", "haga", "devuelva",
    "devuelve", "devuelvo", "detesten", "eligiera", "detestes", "mientan", "mientas", "nazcáis", "mezcles", "mezclen", "continúes", "repares", "rompisteis",
    "continúen", "burlen", "burles", "quiebran", "borde", "organice", "nació", "gruñéramos", "propuse", "añadía", "utilicemos", "propusieron", "dependiéramos",
    "graduemos", "dijeron", "convén", "tape", "dirijáis", "extiendes", "doléis", "encantes", "encanten", "organicemos", "almorcéis", "devoré", "venzo", "cuelguen",
    "tememos", "devore", "pusisteis", "erremos", "duren", "saludéis", "cosan", "cosas", "sucedieras", "sacudió", "sucedieran", "convengamos", "contesten",
    "sabremos", "contestes", "oláis", "bendecía", "influyerais", "mudes", "muden", "prefiráis", "mate", "opusiéramos", "recogió", "huelo", "huela", "huele", "abríais",
    "admitan", "dirija", "admitas", "dirijo", "pude", "sacudieron", "pudo", "conducían", "conducías", "era", "aplaudió", "añadan", "añadas", "paremos",
    "deshago", "deshaga", "maduré", "elegido", "persiguiéramos", "reíste", "améis", "apreció", "deshicimos", "destruí", "realicemos", "hicierais",
    "prometían", "borres", "borren", "podemos", "hagamos", "protegiéramos", "aceptes", "acepten", "partáis", "griten", "grites", "desciendo", "fingió", "previera",
    "prefirieron", "propongan", "propongas", "pidáis", "enoje", "lastime", "recomiendan", "actúas", "actúan", "recomiendas", "decimos", "volvamos", "obtengo",
    "eres", "buceen", "bucees", "pruebes", "estuviera", "prueben", "haz", "destruyo", "yació", "destruyó", "enojen", "parezcáis", "tañerais", "cerré", "midieron",
    "compartieron", "riamos", "contengan", "críes", "críen", "contengas", "cultives", "cultiven", "fuméis", "rompiéramos", "prometí", "quisimos", "descubras",
    "ejercieran", "descubran", "ejercieras", "equivoquemos", "prometió", "cosa", "coso", "conquiste", "traducimos", "contienen", "contienes", "iba", "regale",
    "disgusten", "disgustes", "reñíais", "podáis", "añadáis", "cuenten", "cuentes", "cumplías", "asusten", "cupiera", "asustes", "rehúso", "midamos", "combatamos",
    "rehúse", "rehúsa", "ibas", "iban", "florecieran", "florecieras", "bebíais", "pelee", "baje", "prometéis", "vistierais", "hirvió", "sobrevivió", "atraigamos",
    "parecieran", "parecieras", "comimos", "logré", "consiguieran", "anduviera", "respondas", "exijan", "recogiste", "exijas", "respondan", "partíamos", "duches",
    "duchen", "sorprendo", "incluyo", "sonreíste", "incluyó", "friáis", "diré", "ame", "mantuvieron", "preparemos", "atendiéramos", "logréis", "dibuje", "añadíais",
    "sirve", "sirva", "sirvo", "intente", "valiste", "uníais", "decíamos", "rompierais", "supusierais", "monte", "sacudas", "sacudan", "mantuviéramos", "deshicieras",
    "deshicieran", "decida", "decido", "merendéis", "podré", "podrá", "obtenemos", "prometiéramos", "saldremos", "descendiéramos", "quedes", "queden", "pudieron",
    "finjan", "finjas", "bendijeran", "pides", "supiste", "piden", "pidiendo", "bendijeras", "predijeran", "predijeras", "añadió", "aplaudan", "aplaudas", "previsto",
    "valgo", "valga", "deis", "protejan", "frieron", "protejas", "invadía", "desees", "deseen", "leyó", "evacue", "deshará", "desharé", "evacué", "quisierais", "recicle",
    "rechacéis", "olisteis", "tiréis", "desayune", "mandéis", "mueren", "contengo", "aborde", "asistáis", "contenemos", "cenéis", "diríamos", "fingieron", "dormíais",
    "diviertes", "acabemos", "divierten", "temierais", "renacieras", "riña", "contuvimos", "riñe", "riño", "agoréis", "cause", "riñó", "cumplan", "convierten", "cumplas",
    "compitieron", "cupisteis", "lastimes", "lastimen", "llenéis", "duele", "duela", "duelo", "cenes", "cenen", "eligieron", "introdujerais", "renazcáis", "apoyes", "gradúes",
    "apoyen", "aflijas", "aflijan", "sobrevivan", "reñías", "reñían", "sobrevivas", "cene", "convertíamos", "parta", "parte", "parto", "vuelva", "vuelve", "vuelvo", "leamos",
    "detienen", "predijiste", "detienes", "gruñido", "dais", "agüera", "agüere", "agüero", "cantes", "riñan", "canten", "roto", "elijáis", "puedo", "pueda", "puede", "riñas", "mude",
    "abracemos", "creciéramos", "riñeron", "debíais", "contendré", "detendríamos", "consisto", "consista", "consiste", "atrajeran", "atrajeras", "cumpliera", "prefieran", "elegí",
    "divirtiendo", "descubría", "exigió", "envían", "tiñáis", "envías", "ladres", "ladren", "perdiste", "queríais", "saldría", "arregles", "arreglen", "bañéis", "agradéis", "debió",
    "creo", "crea", "rigiendo", "recogimos", "cogieras", "tosiera", "cogieran", "mande", "mando", "uses", "vinisteis", "reconociéramos", "digo", "preservemos", "compréis", "detiene",
    "quieren", "suenas", "destruyerais", "entendamos", "quieres", "suenan", "sirvas", "apoyamos", "sirvan", "interese", "obtengan", "rías", "rían", "obtengas", "compongamos",
    "compartiendo", "consistíamos", "visten", "trajeras", "trajeran", "vistes", "supisteis", "trabajes", "trabajen", "persiguió", "efectúes", "consiguen", "consigues", "caractericemos",
    "quisieron", "fumen", "fumes", "sube", "suba", "subo", "encante", "escogíais", "empieces", "declaréis", "enflaqueciéramos", "entretuvieran", "dicho", "detuvieras", "detuvieran",
    "diseñe", "somos", "sacudía", "sitúe", "sitúa", "sitúo", "lavemos", "tapéis", "espere", "espera", "recuerden", "pudiste", "recuerdes", "regatees", "regateen", "esperé", "acompañéis",
    "guardes", "averigüen", "averigües", "moríamos", "recogisteis", "aprieten", "aprietes", "servimos", "haréis", "compartáis", "detuviéramos", "bailen", "bailes", "debiéramos", "ilustre",
    "aplaudía", "cumplió", "batáis", "advierten", "declaren", "declares", "adviertes", "regules", "mintió", "consumas", "consuman", "elijan", "decidas", "decidan", "alivies", "consistes",
    "consisten", "alivien", "temamos", "advirtiendo", "fijes", "fijen", "devolvamos", "satisficierais", "saldríais", "visite", "toséis", "murieran", "murieras", "surjan", "maduren",
    "madures", "surjas", "preveas", "condene", "prevean", "agoré", "cuelgue", "preserves", "preserven", "debierais", "diste", "consintierais", "llore", "calméis", "guarde", "hierves",
    "dirijas", "dirijan", "viene", "lloré", "confisquemos", "supón", "repiten", "empiece", "predijisteis", "sacudí", "trajeron", "bendecíais", "dijiste", "contuvisteis", "repitieron",
    "prometía", "podamos", "gobiernan", "convirtierais", "quepo", "dudéis", "quepa", "gobiernas", "vean", "prefirierais", "sacudierais", "exprese", "devoréis", "moviéramos", "debas",
    "deban", "emplees", "empleen", "perdió", "surgiendo", "corriéramos", "reconozcáis", "entendemos", "taño", "olviden", "apoyemos", "olvides", "corrierais", "rompiste", "sirvió",
    "expusieras", "expusieran", "curé", "invite", "freíamos", "niegue", "cure", "hirviéramos", "censuréis", "incluyerais", "limpien", "limpies", "emigré", "enojes", "pegues", "peguen",
    "escondemos", "ocurrías", "ocurrían", "barrierais", "hirvieras", "solamos", "hirvieran", "confíe", "confía", "confío", "sustituíamos", "devolviste", "atraje", "atrajo", "expongamos",
    "supiéramos", "sintiendo", "vistieron", "naveguen", "obtuviéramos", "suspiremos", "navegues", "suframos", "propuesto", "corras", "supierais", "bendecíamos", "conducíais", "insistan",
    "insistas", "despedisteis", "sorprenda", "persigo", "lloréis", "escogiera", "hubo", "requiriera", "dependo", "sigue", "invadías", "servía", "obedecieras", "obedecieran", "convenció",
    "consumió", "tiñéramos", "acuerdas", "acuerdan", "tome", "sustituyó", "invadió", "sustituyo", "invirtamos", "debieras", "debieran", "anhele", "perseguíamos", "volvisteis", "preparan",
    "preparas", "decidió", "consiguiera", "empiecen", "reduzcáis", "rigieras", "decoremos", "rigieran", "introducíais", "vendríamos", "convinierais", "baile", "añadimos", "insisten",
    "supondrías", "supondrían", "gruñó", "contribuyera", "advirtieron", "oíais", "hagan", "hagas", "escondamos", "fingen", "finges", "acampe", "encendiéramos", "levante", "tenemos",
    "cumplía", "aflijamos", "recogiéramos", "dimos", "ofendamos", "afeiten", "afeites", "saldré", "untes", "unten", "conteste", "varía", "varíe", "suelo", "suela", "suele", "esperan",
    "esperas", "bate", "bata", "bato", "encuentro", "borré", "invadáis", "sufro", "sufra", "sufre", "medisteis", "meriendes", "merienden", "borre", "cosieras", "conviniendo", "sufrí")

  var j = 0
}
//      cosieran
//      consumíamos
//      creyerais
//      compitieras
//      tañera
//      entretendrías
//      entretendrían
//      preveía
//      varío
//      dierais
//      detengo
//      dormido
//      teñíamos
//      vivamos
//      ando
//      consiguierais
//      ande
//      establecieras
//      casen
//      establecieran
//      cases
//      veíamos
//      surgieron
//      partan
//      partas
//      resolvamos
//      reduzcamos
//      entienden
//      informe
//      hirviera
//      entiendes
//      encuentra
//      nieguen
//      encuentre
//      mováis
//      invente
//      escribas
//      escriban
//      contribuíamos
//      deshagáis
//      tropiezas
//      tropiezan
//      aconsejen
//      aconsejes
//      admiréis
//      riegue
//      elegíamos
//      acompañemos
//      crucéis
//      doble
//      atendamos
//      constituyeras
//      constituyeran
//      acostumbre
//      acaban
//      acabas
//      repetíamos
//      ofendemos
//      despierta
//      midierais
//      subías
//      prefiramos
//      acostumbré
//      subían
//      comparten
//      dependemos
//      convidéis
//      escogimos
//      abandonéis
//      sugiera
//      tiene
//      dicen
//      surjamos
//      dices
//      presienten
//      presientes
//      extingas
//      extingan
//      leyeron
//      gustes
//      expusiéramos
//      asista
//      asiste
//      asisto
//      informéis
//      aguantes
//      dirigió
//      aguanten
//      emigremos
//      pusierais
//      temimos
//      mire
//      nieves
//      nieven
//      sonrío
//      sonría
//      sonríe
//      gruñera
//      dormí
//      invadas
//      salten
//      saltes
//      invadan
//      miré
//      acortes
//      acorten
//      caímos
//      admitáis
//      conozcáis
//      invades
//      echen
//      cabíais
//      eches
//      contengamos
//      invaden
//      satisfaga
//      unía
//      combatan
//      seguí
//      combatas
//      sabrán
//      hiele
//      hiela
//      curemos
//      destruyeron
//      oigáis
//      maduremos
//      corregía
//      dudes
//      salimos
//      duden
//      movierais
//      averigüemos
//      perdonéis
//      fingías
//      fingían
//      fueron
//      predije
//      predijo
//      sueñes
//      sueñen
//      sueles
//      suelen
//      prefieres
//      funcionéis
//      introduzca
//      sirvieron
//      demuestren
//      demuestres
//      barramos
//      tragues
//      traguen
//      metiste
//      consumía
//      sorprendamos
//      mentíamos
//      querrán
//      producido
//      querrás
//      prosigues
//      unen
//      unes
//      gane
//      declaremos
//      prosiguen
//      cobremos
//      partieron
//      exploré
//      convinieran
//      convinieras
//      sigues
//      explore
//      siguen
//      duchemos
//      encontré
//      encontréis
//      reído
//      pertenezcáis
//      cuesto
//      cuesta
//      cueste
//      avancen
//      avances
//      ofenda
//      ofendo
//      interpretes
//      calienten
//      calientes
//      conviniera
//      apoye
//      apoya
//      fuimos
//      saldrás
//      saldrán
//      corregías
//      situemos
//      lamentes
//      llováis
//      lamenten
//      dijo
//      padezcáis
//      escogierais
//      corrigiéramos
//      quebré
//      aplaudimos
//      convirtamos
//      herede
//      volvierais
//      predigamos
//      hielan
//      respondo
//      hielas
//      responda
//      escuchemos
//      estuvimos
//      cupimos
//      consintiendo
//      mantuvierais
//      atendemos
//      sonríes
//      sonríen
//      bebamos
//      expón
//      consienta
//      consiente
//      trajiste
//      atrayendo
//      detendrías
//      detendrían
//      subas
//      suban
//      dirías
//      predices
//      predicen
//      sustituyes
//      sustituyen
//      agradezcáis
//      satisfagáis
//      añadierais
//      descendamos
//      funcione
//      convirtieron
//      podrías
//      podrían
//      satisficiera
//      vendréis
//      atrajiste
//      torcieras
//      gruñíais
//      torcieran
//      corrigiendo
//      descubramos
//      beban
//      bebas
//      borremos
//      registren
//      bates
//      opusieron
//      baten
//      perseguí
//      conducimos
//      presintiendo
//      exhibáis
//      cabríais
//      haya
//      sugeríais
//      duermes
//      aplaudían
//      aplaudías
//      duermen
//      olvido
//      juremos
//      convendremos
//      celebren
//      reíd
//      celebres
//      produzcáis
//      salve
//      oísteis
//      devolvió
//      bese
//      tengamos
//      obtuvieras
//      obtuvieran
//      muráis
//      vais
//      regales
//      gobierno
//      caído
//      gobierna
//      eliges
//      derriten
//      derrites
//      eligen
//      caísteis
//      gastes
//      firmes
//      firmen
//      solemos
//      prometiera
//      olamos
//      bendecimos
//      sucediste
//      satisfagas
//      compartamos
//      halle
//      perdieran
//      perdieras
//      descubrió
//      protesten
//      protestes
//      cupieras
//      tiñerais
//      huelas
//      huelan
//      despida
//      despide
//      despido
//      llovamos
//      pidamos
//      vea
//      venga
//      vengo
//      reísteis
//      tañeran
//      riñerais
//      tañeras
//      cayeron
//      cupierais
//      sonrió
//      escojáis
//      peleéis
//      atraviesas
//      atraviesan
//      sepan
//      sepas
//      gradué
//      revelen
//      hirieras
//      hirieran
//      reveles
//      pierda
//      pierde
//      duelen
//      vote
//      están
//      empiezas
//      estás
//      varían
//      propusimos
//      corrieras
//      necesiten
//      necesites
//      herías
//      muriendo
//      rierais
//      sustituyeran
//      consentíamos
//      sustituyeras
//      robe
//      traigas
//      traigan
//      despiertan
//      despiertas
//      corra
//      corro
//      derritiéramos
//      opón
//      barrieran
//      barrieras
//      muriéramos
//      convendrían
//      mantuvieran
//      mantuvieras
//      convendrías
//      soliéramos
//      dijeran
//      dijeras
//      echéis
//      participe
//      supimos
//      consintáis
//      viniendo
//      acostumbremos
//      acuesto
//      acueste
//      acuesta
//      valemos
//      contuviste
//      distinguen
//      estuviste
//  case
//  pondrías
//  pondrían
//  consistáis
//  medían
//  traduciendo
//  medías
//  debiera
//  cace
//  recogíais
//  probéis
//  regían
//  pintes
//  pinten
//  quisiera
//  amanezcáis
//  sequemos
//  compartes
//  metido
//  consigo
//  ahorremos
//  subió
//  averigüéis
//  opondríamos
//  supiera
//  seamos
//  sorprendan
//  sugerido
//  sorprendas
//  bebiéramos
//  aburrido
//  protegierais
//  enseñemos
//  admitamos
//  batamos
//  persiguiera
//  diseñemos
//  siguiera
//  herido
//  bebió
//  estuvisteis
//  cabrás
//  cabrán
//  protegimos
//  pudisteis
//  aplaudierais
//  extinga
//  extingo
//  leemos
//  saldréis
//  dolieran
//  unáis
//  disfruten
//  disfrutes
//  canse
//  dolieras
//  convendréis
//  salgan
//  salgas
//  afirmen
//  afirmes
//  presintieron
//  frías
//  frían
//  bendijisteis
//  expuse
//  atrajera
//  expuso
//  celebréis
//  compusiste
//  ejerciéramos
//  traigamos
//  resulte
//  llame
//  quiebro
//  quiebre
//  quiebra
//  pierdan
//  leo
//  asistas
//  asistan
//  cuelgo
//  cuelga
//  corrigierais
//  insisto
//  insiste
//  insista
//  reparen
//  sucediéramos
//  dolió
//  cabréis
//  nado
//  metíais
//  cese
//  quiebras
//  escuchen
//  escuches
//  trajera
//  sintiéramos
//  desagradezcáis
//  yerro
//  yerra
//  yerre
//  emplee
//  avance
//  repita
//  repite
//  repito
//  abrace
//  plantes
//  planten
//  cogíais
//  mueves
//  mueven
//  resolviéramos
//  devuelto
//  fortalezcáis
//  predijéramos
//  nieva
//  nieve
//  nievo
//  devuelves
//  presintáis
//  soñemos
//  devuelven
//  contén
//  vuelvan
//  estés
//  estén
//  consintieras
//  indujerais
//  prefiriera
//  desapareciéramos
//  continuemos
//  huyeran
//  huyeras
//  saldrían
//  saldrías
//  lluevas
//  guardéis
//  introducíamos
//  luchemos
//  meto
//  puedes
//  metierais
//  consumáis
//  acuestas
//  acuestan
//  registréis
//  despidan
//  permita
//  despidas
//  divirtieron
//  debimos
//  rechacen
//  rechaces
//  corrigieras
//  sirvierais
//  corrigieran
//  soñéis
//  disfrute
//  vayáis
//  llaméis
//  sustituyera
//  insistamos
//  bendijeron
//  di
//  dependa
//  aspiréis
//  compitáis
//  repitierais
//  hicisteis
//  siguiéramos
//  alquiles
//  confirmen
//  obtén
//  confirmes
//  sufráis
//  fortalecieras
//  fortalecieran
//  valdrías
//  valdrían
//  cumpláis
//  dieran
//  predicho
//  prueban
//  aburramos
//  cubriendo
//  satisfizo
//  corrijan
//  cruces
//  crucen
//  corrijas
//  cumpla
//  cumple
//  convenías
//  convenían
//  cumplí
//  sacudimos
//  emborrache
//  advirtamos
//  salvemos
//  consistiendo
//  sacudido
//  torzamos
//  vaya
//  prometíais
//  explotes
//  exploten
//  es
//  bordéis
//  jueguen
//  registremos
//  juegues
//  gruñerais
//  cupiste
//  recojamos
//  quisieran
//  freíais
//  expondríamos
//  dormíamos
//  mantiene
//  debisteis
//  comprendas
//  vienen
//  creyeron
//  vienes
//  ocurren
//  conoció
//  ocurres
//  aprueban
//  apruebas
//  pongas
//  pongan
//  siguieron
//  enamore
//  aflijo
//  sois
//  enamoré
//  predijimos
//  escogió
//  vendrías
//  extendiéramos
//  vendrían
//  resuelves
//  resuelven
//  sonéis
//  dolierais
//  actuéis
//  harías
//  harían
//  proteste
//  prepara
//  describo
//  venza
//  sales
//  describa
//  salen
//  preparé
//  cuelgues
//  hervíamos
//  pedíais
//  bebáis
//  tañéramos
//  rueguen
//  satisfaz
//  robes
//  roben
//  previerais
//  almuerzan
//  confiesas
//  confiesan
//  almuerzas
//  fortaleciéramos
//  tañisteis
//  subiendo
//  convienes
//  convienen
//  vi
//  funcionen
//  brinden
//  brindes
//  funciones
//  descendemos
//  actuemos
//  odies
//  odien
//  cojamos
//  cubramos
//  hiriéramos
//  detuvisteis
//  condenéis
//  sugería
//  oiga
//  oigo
//  dirá
//  podréis
//  prefiriendo
//  imprimas
//  impriman
//  traído
//  alcancéis
//  desagradecieran
//  desagradecieras
//  valdríamos
//  supuesto
//  duchéis
//  hervíais
//  expusiste
//  empleéis
//  satisfarán
//  sucedemos
//  satisfarás
//  dijera
//  hiciéramos
//  despidió
//  bañes
//  bañen
//  escondiéramos
//  suspiré
//  ruegas
//  ruegan
//  convierto
//  sugirió
//  gradúen
//  insulten
//  vengas
//  morían
//  leyerais
//  morías
//  viniera
//  culpemos
//  usen
//  advirtáis
//  sacudíamos
//  abrías
//  dures
//  abrían
//  sorprendiéramos
//  amenacemos
//  pusimos
//  consiguiéramos
//  finjáis
//  reparéis
//  leyendo
//  detuvimos
//  predijeron
//  leyera
//  cultivéis
//  cumplíamos
//  cayendo
//  cosiste
//  satisfaríais
//  comiste
//  evacuéis
//  tuerce
//  efectúa
//  efectúe
//  deprimáis
//  hielo
//  estuvierais
//  satisficiste
//  frieran
//  prefiriéramos
//  frieras
//  entren
//  entres
//  corran
//  enseñe
//  permaneciéramos
//  metáis
//  abren
//  abres
//  habría
//  freíste
//  derritamos
//  padecieran
//  padecieras
//  convinimos
//  consumiendo
//  renovéis
//  borden
//  bordes
//  resolviste
//  aburren
//  aburres
//  corráis
//  niegues
//  reconoció
//  subía
//  comienzas
//  comienzan
//  gusten
//  ofendas
//  ofendan
//  enciendas
//  enciendan
//  sabríais
//  consientas
//  preferíais
//  deposite
//  consientan
//  sonreído
//  dijéramos
//  enriquecieras
//  sucedamos
//  enriquecieran
//  prefieren
//  recogiera
//  bendijerais
//  escondiera
//  persiguiendo
//  escojamos
//  bendicen
//  bendices
//  efectúas
//  tuerces
//  tuercen
//  efectúan
//  estudien
//  estudies
//  insulte
//  dirían
//  duréis
//  midiendo
//  disminuyo
//  olvide
//  respiremos
//  disminuyó
//  civilicemos
//  gasten
//  abierto
//  hieres
//  hieren
//  escribamos
//  servido
//  dependamos
//  hizo
//  olió
//  vestíamos
//  crío
//  alienten
//  alientes
//  calmen
//  abortes
//  aborten
//  distribuyeron
//  atraviesa
//  atraviese
//  atravieso
//  prohíbo
//  prohíbe
//  prohíba
//  convengan
//  eligierais
//  convengas
//  sonriéramos
//  escogieras
//  escogieran
//  acabes
//  lastiméis
//  supongamos
//  condujerais
//  maneje
//  imprimió
//  salíais
//  oigamos
//  traducíais
//  lluevan
//  reías
//  reían
//  produzcamos
//  arrojen
//  arrojes
//  protegiste
//  hiciste
//  murió
//  redujerais
//  introduzco
//  hicieron
//  gobernéis
//  digáis
//  viajes
//  viajen
//  envejezcáis
//  obtendríamos
//  surgías
//  surgían
//  aflija
//  molestes
//  molesten
//  exportes
//  tropieces
//  exporten
//  tropiecen
//  distinga
//  distingo
//  propondríamos
//  vengan
//  entretengo
//  empiezo
//  prevé
//  distribuíamos
//  cojas
//  cojan
//  rigió
//  compitiendo
//  disteis
//  andéis
//  colonice
//  sacudamos
//  sirvamos
//  obtuvimos
//  defiendo
//  floreciéramos
//  fije
//  enciendo
//  corrió
//  mintieron
//  muevo
//  mueva
//  mueve
//  marquemos
//  bucee
//  tañiste
//  componemos
//  exijáis
//  entusiasmes
//  entretiene
//  freísteis
//  sirviera
//  barra
//  desharíamos
//  barro
//  constituyeron
//  encuentran
//  encuentras
//  hecho
//  fume
//  derritierais
//  tiñamos
//  regule
//  puedan
//  puedas
//  exhiban
//  empecéis
//  cuidéis
//  ocurrieron
//  defendemos
//  satisficiéramos
//  movieran
//  movieras
//  comencéis
//  entiendo
//  aspiremos
//  madure
//  prosiguiendo
//  guía
//  guíe
//  renovemos
//  entretienen
//  entretienes
//  bebiste
//  sorprendemos
//  cosáis
//  preveo
//  prometías
//  planche
//  prevea
//  des
//  den
//  consigamos
//  unimos
//  compondríamos
//  corregido
//  convengo
//  convenga
//  protegíais
//  corregí
//  influyeron
//  deshecho
//  predigo
//  ruego
//  ruega
//  soléis
//  sonrías
//  sientas
//  preferían
//  preferías
//  sientan
//  íbamos
//  traduzca
//  traduzco
//  cubráis
//  heríais
//  fue
//  fui
//  llovisteis
//  convirtiendo
//  cuesten
//  llovió
//  cuestes
//  invirtierais
//  ejerció
//  sugiráis
//  fuéramos
//  respete
//  invadí
//  servían
//  servías
//  cogierais
//  deshagas
//  deshagan
//  invado
//  guías
//  guían
//  exhibas
//  pares
//  vuelen
//  vueles
//  paren
//  trajimos
//  muestra
//  muestre
//  muestro
//  incluí
//  surgía
//  entusiasmen
//  escogisteis
//  huyerais
//  podrás
//  podrán
//  dirán
//  dirás
//  persigue
//  matricule
//  quebremos
//  extinguíamos
//  sonrierais
//  comprendemos
//  obtengamos
//  falte
//  reí
//  corrigen
//  producíamos
//  tuvisteis
//  corriges
//  invadiendo
//  curen
//  cures
//  renueves
//  renueven
//  produjerais
//  rompamos
//  deteste
//  desharíais
//  anduviéramos
//  conduciendo
//  queráis
//  enamoremos
//  distribuyen
//  charlen
//  interpreten
//  convendría
//  probemos
//  pedías
//  consintió
//  bautice
//  pedían
//  valiéramos
//  sugieres
//  sugieren
//  viniste
//  dependas
//  dependan
//  teñido
//  sonriendo
//  decíais
//  podría
//  detuvieron
//  defendiéramos
//  barrías
//  atiendas
//  atiendan
//  anden
//  andes
//  olemos
//  añadiendo
//  cubrieron
//  persigamos
//  defendamos
//  cumplíais
//  induzcáis
//  anhelen
//  vayamos
//  anheles
//  afirméis
//  previeras
//  opusiste
//  previeran
//  introducían
//  introducías
//  gruñed
//  gruñen
//  gruñes
//  regatee
//  diera
//  bendijéramos
//  eche
//  cante
//  quisiéramos
//  guío
//  entretuvimos
//  duremos
//  cierres
//  cierren
//  dijimos
//  entusiasméis
//  serví
//  cayó
//  recemos
//  cacemos
//  compuso
//  compuse
//  entretuvieras
//  protejáis
//  rigieron
//  interprete
//  doliste
//  sintieran
//  sintieras
//  quepas
//  quepan
//  oléis
//  sepa
//  predecíamos
//  deshagamos
//  producíais
//  tuviste
//  adore
//  aplaudáis
//  lancéis
//  junte
//  adoré
//  recogieran
//  decidáis
//  opusimos
//  oigas
//  dije
//  prohibáis
//  bebimos
//  satisfarían
//  satisfarías
//  prosigo
//  situéis
//  culpe
//  rehúses
//  rehúsen
//  enfaden
//  invirtéramos
//  enfades
//  aburrí
//  andáis
//  añadían
//  añadías
//  prevés
//  prevén
//  aburra
//  saliendo
//  cayeran
//  aburro
//  cayeras
//  predijerais
//  acepte
//  extingáis
//  miden
//  elegía
//  mides
//  requirieron
//  invierten
//  devoremos
//  mates
//  inviertes
//  chismeéis
//  prosigan
//  supusieron
//  huí
//  aburriendo
//  corten
//  cortes
//  tuviéramos
//  sustituyeron
//  recojo
//  miremos
//  competíamos
//  durmamos
//  perdiéramos
//  censuremos
//  hirierais
//  oí
//  desharán
//  desharás
//  salude
//  calmes
//  venzan
//  venzas
//  perdiera
//  finjamos
//  hirviendo
//  durmieran
//  durmieras
//  reñíamos
//  opongamos
//  simbolicemos
//  añadíamos
//  supondré
//  ten
//  cosisteis
//  agradeciéramos
//  abandonen
//  hirvamos
//  invirtáis
//  consistieron
//  levantes
//  sobreviva
//  sobrevivo
//  muestren
//  muestres
//  traigáis
//  escondo
//  valierais
//  obtiene
//  esconda
//  hubiera
//  saliera
//  trajéramos
//  cupo
//  predecía
//  reducíamos
//  convinisteis
//  pedido
//  compartíamos
//  combatieron
//  ladremos
//  divirtió
//  deje
//  defiendes
//  riéramos
//  engañe
//  defienden
//  leyeran
//  leyeras
//  almuerce
//  sabréis
//  dormías
//  conducíamos
//  acuerde
//  acuerda
//  acuerdo
//  regía
//  venció
//  requieras
//  requieran
//  hago
//  medí
//  compón
//  inducido
//  apoyéis
//  sugirieras
//  diéramos
//  subieron
//  obedeciéramos
//  aplaudo
//  aplaude
//  venzáis
//  aplauda
//  piensas
//  inducíais
//  hiera
//  piensan
//  opusierais
//  aplaudí
//  castigues
//  use
//  cupieron
//  demuestre
//  demuestra
//  demuestro
//  oíamos
//  niegan
//  desciendas
//  desciendan
//  reducido
//  cierra
//  bendijimos
//  valgáis
//  sugeríamos
//  preveíamos
//  nevemos
//  requiera
//  aparecieras
//  advirtió
//  almuercen
//  almuerces
//  creyéramos
//  obtuvisteis
//  yerren
//  yerres
//  expusisteis
//  sirvieras
//  rige
//  sirvieran
//  sabría
//  compres
//  tapemos
//  ahorren
//  ahorres
//  insistiendo
//  extiendan
//  extiendas
//  sabrían
//  sabrías
//  resuelto
//  corriste
//  consigan
//  consigas
//  trayendo
//  sufren
//  sufres
//  subamos
//  apueste
//  consumo
//  juréis
//  cumplían
//  dieron
//  describamos
//  imprimamos
//  enfadéis
//  ruegues
//  compitiéramos
//  traducido
//  sepamos
//  muramos
//  amenaces
//  invada
//  amenacen
//  diríais
//  devolviéramos
//  aburrieron
//  leáis
//  sonriáis
//  riñen
//  temas
//  teman
//  riñes
//  comparte
//  comparta
//  comparto
//  amaneciéramos
//  dejen
//  dejes
//  divirtieras
//  divirtieran
//  medíamos
//  incluíamos
//  surgió
//  compito
//  compite
//  compita
//  traduzcáis
//  asistíamos
//  extendamos
//  confíes
//  tosisteis
//  confíen
//  permanezcáis
//  planchéis
//  consumías
//  conducido
//  consumían
//  propuso
//  temáis
//  gruñáis
//  debo
//  sucedió
//  deba
//  detuviste
//  elijo
//  elija
//  quisisteis
//  olvidéis
//  derritiera
//  estuvieron
//  prohíbas
//  prohíban
//  agüeren
//  agüeres
//  riera
//  son
//  soy
//  resultes
//  resulten
//  encuentren
//  conjuguen
//  siguió
//  conjugues
//  regíamos
//  saquemos
//  recibamos
//  tendrías
//  colonicemos
//  logre
//  tendrían
//  descubrías
//  diremos
//  juré
//  invade
//  cubres
//  bebieran
//  sigo
//  bebieras
//  actúe
//  actúa
//  cubren
//  actúo
//  jure
//  viaje
//  esquías
//  esquían
//  construyen
//  sé
//  construyes
//  gruñimos
//  aburráis
//  presintieran
//  presintieras
//  averigüé
//  escogiste
//  obtendrían
//  obtendrías
//  cubrías
//  averigüe
//  quepáis
//  rompas
//  rompan
//  abracéis
//  hiramos
//  convenza
//  ilustres
//  convenzo
//  consiguieras
//  ilustren
//  comprendiéramos
//  arregle
//  entretenemos
//  debamos
//  deshizo
//  atraigo
//  entretuviéramos
//  pidiera
//  barriéramos
//  aburríamos
//  elijas
//  harás
//  harán
//  ocurramos
//  veas
//  tañas
//  tañan
//  constituí
//  soporten
//  soportes
//  duelas
//  duelan
//  mintáis
//  resuelva
//  satisfecho
//  induciendo
//  pondríamos
//  pudiendo
//  insistáis
//  detenemos
//  anduviste
//  envejecieran
//  mientes
//  abramos
//  envejecieras
//  mienten
//  gruñe
//  gruña
//  gruño
//  obligues
//  obliguen
//  culpen
//  culpes
//  gruñí
//  firméis
//  predigáis
//  comisteis
//  teñimos
//  despedían
//  muriera
//  gruñendo
//  borréis
//  efectuemos
//  vacíes
//  cancelen
//  vacíen
//  sitúes
//  podremos
//  sitúen
//  estuviéramos
//  generalicemos
//  adornen
//  adornes
//  está
//  tuerzan
//  tiñen
//  tiñes
//  confirméis
//  nacieras
//  nacieran
//  contribuyeron
//  satisfago
//  caracterice
//  leyéramos
//  aconseje
//  temió
//  murierais
//  afligió
//  escondiste
//  proseguí
//  corregíamos
//  leísteis
//  desayunes
//  protegió
//  desayunen
//  disminuyeron
//  extendemos
//  hervimos
//  movamos
//  acabe
//  acaba
//  vendas
//  vendan
//  atrajisteis
//  atrajimos
//  desharéis
//  fría
//  fríe
//  frío
//  comiera
//  consigáis
//  pidierais
//  atraigáis
//  continué
//  compites
//  compiten
//  tosáis
//  corrieran
//  herían
//  valisteis
//  oyera
//  surjáis
//  creyó
//  convenimos
//  inventes
//  inventen
//  conviniéramos
//  consintamos
//  convendré
//  convendrá
//  requiriendo
//  rompieras
//  alquile
//  rompieran
//  bendiciendo
//  llevemos
//  durmiendo
//  metí
//  meta
//  vierais
//  renaciéramos
//  midiera
//  tuvierais
//  descubríais
//  protejamos
//  recomienden
//  recomiendes
//  buceéis
//  recéis
//  pruebas
//  apuestan
//  luchen
//  luches
//  apuestas
//  rompió
//  crecieras
//  efectué
//  crecieran
//  cojo
//  cosamos
//  convenzamos
//  satisficisteis
//  inviten
//  barras
//  barran
//  invites
//  hirváis
//  yacieras
//  cumplamos
//  va
//  aliente
//  alienta
//  aliento
//  cubríais
//  satisfice
//  creyeran
//  sacudisteis
//  creyeras
//  metías
//  mantienen
//  mantienes
//  metían
//  adornéis
//  enferme
//  registre
//  invadimos
//  admiremos
//  mandes
//  manden
//  veis
//  diseñéis
//  decían
//  renuevo
//  renueve
//  renueva
//  decías
//  permitáis
//  gobierne
//  corrías
//  venimos
//  corrían
//  regalen
//  aburrían
//  aburrías
//  traje
//  trajo
//  cuentas
//  cuentan
//  deshiciera
//  vendría
//  leíste
//  revele
//  querríamos
//  distinguí
//  huíamos
//  cayéramos
//  barriera
//  empieza
//  distingue
//  querremos
//  erréis
//  consiguiendo
//  consintieron
//  reparas
//  reparan
//  dibujes
//  quiebres
//  quiebren
//  dibujen
//  regrese
//  enflaquezcáis
//  distribuyeran
//  oía
//  oíd
//  distribuyeras
//  continúan
//  continúas
//  exhibamos
//  diréis
//  prosigamos
//  requerí
//  compusieron
//  presienta
//  presiente
//  presiento
//  pudimos
//  conseguíamos
//  ocurriendo
//  sirváis
//  hieles
//  cosió
//  olieras
//  olieran
//  creamos
//  quebréis
//  combatáis
//  rieran
//  rieras
//  rompiera
//  cepillen
//  oigan
//  cepilles
//  recogieras
//  quede
//  corrigieron
//  invirtió
//  reducíais
//  bendijiste
//  converse
//  pidieras
//  perdemos
//  queríamos
//  ayuden
//  ayudes
//  aprieto
//  apriete
//  aprieta
//  incluyeron
//  cubrí
//  charles
//  presenten
//  presentes
//  cubre
//  cubra
//  cubro
//  requeríamos
//  influyera
//  florezcáis
//  niegas
//  compusimos
//  batieron
//  pidió
//  propongamos
//  forme
//  calme
//  almuerza
//  almuerzo
//  tosió
//  añades
//  añaden
//  seguíamos
//  sonrían
//  persigues
//  persiguen
//  midáis
//  devolviera
//  descubres
//  bañemos
//  acampéis
//  mintieran
//  brillen
//  despidieras
//  vendremos
//  despidieran
//  mintieras
//  brilles
//  valdré
//  pese
//  opuso
//  opuse
//  prometido
//  informen
//  cumpliendo
//  construyerais
//  triunfe
//  informes
//  teñía
//  sirviéramos
//  canceles
//  eran
//  eras
//  riego
//  invoquemos
//  actúen
//  actúes
//  efectuéis
//  barrió
//  prometierais
//  produzca
//  produzco
//  mueran
//  crías
//  tengo
//  crían
//  mueras
//  tosiste
//  propusisteis
//  distinguíamos
//  aprobemos
//  deseéis
//  aplaudiendo
//  laven
//  laves
//  cumples
//  cumplen
//  introduzcamos
//  fingía
//  veo
//  deshaz
//  siguieras
//  obtienes
//  obtienen
//  siguieran
//  propusierais
//  descubren
//  situé
//  triunféis
//  requirierais
//  moríais
//  decía
//  rece
//  juegue
//  hiriendo
//  añadisteis
//  recojáis
//  exija
//  atraído
//  veníais
//  prometiste
//  contuvieron
//  juega
//  juego
//  destruyeran
//  mantendré
//  rija
//  salga
//  salgo
//  cuelgan
//  cuelgas
//  censuré
//  consume
//  descubierto
//  pusiéramos
//  censure
//  logremos
//  fingí
//  ilustremos
//  finge
//  confieso
//  confiesa
//  confiese
//  prediciendo
//  comierais
//  consistamos
//  exijo
//  pertenecieras
//  pertenecieran
//  frierais
//  divirtierais
//  envíes
//  envíen
//  tiñeron
//  requiramos
//  pelees
//  decoré
//  peleen
//  regateéis
//  decore
//  toquemos
//  añadí
//  resolvieras
//  unamos
//  añada
//  añado
//  sacuden
//  introduciendo
//  ponemos
//  satisfará
//  satisfaré
//  despedíamos
//  disminuyerais
//  engañemos
//  freíd
//  quieran
//  suenes
//  quieras
//  pidan
//  pidas
//  vendemos
//  estiméis
//  tire
//  temisteis
//  ataquemos
//  hirió
//  respondiéramos
//  convendríais
//  cerréis
//  disminuí
//  tiré
//  protegiera
//  aplaudes
//  tosas
//  comemos
//  tosan
//  construyeras
//  construyeran
//  mintiendo
//  hallen
//  halles
//  rijo
//  teñías
//  elige
//  ocurráis
//  debiste
//  aparecieran
//  venías
//  venían
//  corristeis
//  cumplimos
//  prosiguiera
//  vendré
//  friendo
//  compitamos
//  vistamos
//  tuerza
//  invadamos
//  tuerzo
//  cultive
//  recuerdan
//  inmigré
//  recuerdas
//  invadido
//  estuvo
//  estuve
//  inmigre
//  encendemos
//  construí
//  sentíamos
//  alegré
//  estimes
//  sacude
//  sacuda
//  tosiéramos
//  pedisteis
//  aprietas
//  dirijamos
//  invirtieron
//  alegre
//  recibáis
//  registres
//  cabremos
//  extingue
//  resolvisteis
//  diviertan
//  diviertas
//  sigamos
//  extinguí
//  sigan
//  sigas
//  varías
//  agraden
//  agrades
//  empiezan
//  adviertas
//  adviertan
//  conviertas
//  doy
//  despidiera
//  conviertan
//  inmigréis
//  entretendríamos
//  consistan
//  convenzan
//  detuvierais
//  une
//  consistas
//  convenzas
//  uno
//  desayunéis
//  metamos
//  construyó
//  protegieras
//  protegieran
//  aburríais
//  construyo
//  compongas
//  vengáis
//  conocieran
//  conocieras
//  vendo
//  abraces
//  conservemos
//  vistieran
//  entretengamos
//  expusierais
//  envía
//  envíe
//  envío
//  vuela
//  vuele
//  fuisteis
//  vuelo
//  despedí
//  medíais
//  demostréis
//  subáis
//  contribuyo
//  vencieran
//  vencieras
//  vendríais
//  hiervas
//  hiervan
//  contribuyó
//  dijerais
//  comienza
//  comienzo
//  pregunte
//  ocurrido
//  repase
//  vistiera
//  llenen
//  llenes
//  gobiernes
//  gobiernen
//  teñíais
//  advierto
//  hicieras
//  hicieran
//  deprima
//  tropiezo
//  tropieza
//  deprimo
//  repitáis
//  aplaudido
//  requirieran
//  invadíais
//  requirieras
//  estoy
//  dice
//  sustituí
//  supusieras
//  supusieran
//  vendamos
//  riegan
//  traduzcas
//  riegas
//  traduzcan
//  llamen
//  llames
//  avise
//  satisfaréis
//  cruce
//  satisficimos
//  bendigáis
//  sirves
//  sirven
//  escuchéis
//  nadéis
//  disminuyera
//  exijamos
//  convendríamos
//  supieron
//  venía
//  aplaudisteis
//  presentíamos
//  ríen
//  tuerzas
//  reñido
//  sueña
//  sueñe
//  sueño
//  vistas
//  aguante
//  vistan
//  brindáis
//  respondiste
//  participemos
//  prefirieran
//  bañe
//  extinguiendo
//  distribuyerais
//  induzcamos
//  predijera
//  desharían
//  desharías
//  venzamos
//  podríais
//  veía
//  aprendemos
//  felicite
//  haré
//  hará
//  soliste
//  ganes
//  servíamos
//  ganen
//  encendamos
//  soláis
//  tiremos
//  para
//  distribuí
//  rigiera
//  pudieran
//  pudieras
//  declara
//  declare
//  hervía
//  mueres
//  paré
//  atrajerais
//  declaré
//  repases
//  repasen
//  acampemos
//  aumentes
//  bendigan
//  aumenten
//  convides
//  conviden
//  tosemos
//  despidamos
//  declaras
//  devolvierais
//  declaran
//  constituyera
//  induzcan
//  induzcas
//  amenace
//  produciendo
//  hiráis
//  dijisteis
//  unías
//  unían
//  traten
//  pongamos
//  entretendré
//  vivan
//  vivas
//  fríes
//  prefería
//  invadieron
//  sugirieron
//  influyeras
//  preparen
//  bendijera
//  prepares
//  influyeran
//  perdamos
//  hablen
//  hables
//  dolamos
//  pudierais
//  planchen
//  planches
//  sonreíamos
//  descrito
//  intentes
//  reserven
//  reserves
//  unido
//  obedezcáis
//  compré
//  recuerda
//  recuerde
//  recuerdo
//  añade
//  sucediera
//  compre
//  agrado
//  agrade
//  repitas
//  induzca
//  induzco
//  repitan
//  permitamos
//  requería
//  creyendo
//  atraigan
//  atraigas
//  crucemos
//  visites
//  visiten
//  compondré
//  bendice
//  sacudes
//  queréis
//  perdone
//  entendiéramos
//  tosieran
//  abrieron
//  aplaudamos
//  efectúo
//  tosieras
//  propondré
//  controle
//  compondrías
//  compondrían
//  valgan
//  devolváis
//  valgas
//  tuvieron
//  renacieran
//  preferíamos
//  desaparecieran
//  friéramos
//  entretuvierais
//  tiño
//  tiñe
//  tiña
//  destruyes
//  prosiguió
//  destruyen
//  creemos
//  tiñó
//  expongan
//  propusiste
//  expongas
//  desarrolle
//  sobrevivamos
//  diciendo
//  mantengan
//  pareciéramos
//  mantengas
//  exploréis
//  montes
//  monten
//  incluyera
//  pido
//  pida
//  pide
//  vistió
//  viéramos
//  parten
//  opusisteis
//  partes
//  enriqueciéramos
//  salvéis
//  corrigiera
//  entiendas
//  entiendan
//  consiguió
//  advirtiéramos
//  conviertes
//  instale
//  contribuyerais
//  friera
//  durmieron
//  aspiré
//  mintierais
//  batíamos
//  deshiciéramos
//  padeciéramos
//  sacudíais
//  sugieras
//  combate
//  combata
//  combato
//  temiera
//  triunfen
//  prometáis
//  ladréis
//  riáis
//  valgamos
//  regí
//  previsteis
//  querían
//  preservéis
//  querías
//  lleves
//  lleven
//  engañéis
//  combatíamos
//  prosiguieron
//  tosamos
//  insistes
//  oliéramos
//  viváis
//  presientan
//  presientas
//  surgíamos
//  influyen
//  viniéramos
//  quepamos
//  metimos
//  trajisteis
//  estuvieran
//  estuvieras
//  echemos
//  merendáis
//  llueve
//  llueva
//  lluevo
//  resolvió
//  cayera
//  sienta
//  siente
//  enseñen
//  siento
//  acuerdes
//  adoréis
//  acuerden
//  preveían
//  preveías
//  pedí
//  reñí
//  veíais
//  resolviera
//  suenen
//  regías
//  teñían
//  vivió
//  amenacéis
//  extinguen
//  extingues
//  volvió
//  abríamos
//  cobren
//  cancele
//  cobres
//  respondiera
//  aplaudíais
//  carguen
//  conquisten
//  conquistes
//  introduzcáis
//  satisfagan
//  cupieran
//  producimos
//  riñendo
//  salido
//  querríais
//  desee
//  metiéramos
//  viva
//  acabéis
//  construíamos
//  pon
//  rechacemos
//  distingues
//  sucedan
//  demostremos
//  repitió
//  supusiéramos
//  aplauden
//  advertíamos
//  valéis
//  caigáis
//  unas
//  unan
//  cultivemos
//  ocurríais
//  esperes
//  esperen
//  veamos
//  reñimos
//  invirtiendo
//  finjo
//  compitiera
//  ejerzas
//  ejerzan
//  alquilen
//  oyó
//  dieras
//  gruñamos
//  meriendan
//  preferí
//  meriendas
//  instalen
//  instales
//  gruñeron
//  obtuvierais
//  tardéis
//  repitiendo
//  moleste
//  insultes
//  maduréis
//  contribuyeran
//  contribuyeras
//  meriende
//  merienda
//  meriendo
//  depriman
//  deprimas
//  elijamos
//  ejerzáis
//  participéis
//  entretuvieron
//  desharemos
//  servíais
//  oyen
//  cosemos
//  anduvimos
//  oyes
//  nades
//  naden
//  resolváis
//  plante
//  cría
//  críe
//  sugiramos
//  viole
//  cubierto
//  acaben
//  movisteis
//  investiguen
//  compartas
//  compartan
//  investigues
//  pedimos
//  persigáis
//  salieron
//  envejeciéramos
//  diseñen
//  diseñes
//  acontezcáis
//  descubriendo
//  gradúan
//  merezcáis
//  supuso
//  supuse
//  cabríamos
//  convengáis
//  ocurría
//  divertíamos
//  mantuvisteis
//  exploremos
//  durmáis
//  conveníais
//  abuse
//  batan
//  batas
//  nievan
//  nievas
//  compitierais
//  barrían
//  cambies
//  cambien
//  alcancemos
//  sea
//  acontecieras
//  acontecieran
//  supondríamos
//  salía
//  caigas
//  vio
//  riñéramos
//  vendrás
//  entreguen
//  entregues
//  vendrán
//  riendo
//  amen
//  combaten
//  combates
//  ames
//  contribuí
//  querrá
//  querré
//  sintieron
//  adoremos
//  señalen
//  señales
//  describáis
//  abandones
//  derritáis
//  gaste
//  creímos
//  añadido
//  bebiera
//  planchemos
//  creyera
//  respetes
//  tañamos
//  entréis
//  obtendré
//  junten
//  hueles
//  quisiste
//  subido
//  huelen
//  juntes
//  suelan
//  suelas
//  van
//  vas
//  anduvieras
//  chismee
//  anduvieran
//  tema
//  temo
//  bebisteis
//  sabrá
//  hicimos
//  sabré
//  demuestras
//  sueñan
//  sueñas
//  demuestran
//  escriba
//  escribo
//  herí
//  sucedo
//  suceda
//  sonreí
//  reportes
//  reporten
//  querría
//  controles
//  cupiéramos
//  controlen
//  abre
//  convenía
//  abra
//  descubrían
//  abro
//  unió
//  conociéramos
//  presintamos
//  traducíamos
//  varíes
//  metéis
//  varíen
//  resuelvo
//  incluyen
//  resuelve
//  incluyes
//  despiertes
//  despierten
//  sirviendo
//  aplaudieron
//  nevéis
//  barráis
//  riñera
//  calientas
//  calientan
//  veáis
//  satirice
//  vinieran
//  frió
//  vinieras
//  pusiste
//  abrí
//  digamos
//  almorcemos
//  durmierais
//  salgáis
//  conveníamos
//  yacieran
//  compusisteis
//  maten
//  subíamos
//  prosigas
//  cuides
//  falten
//  hielen
//  faltes
//  cuiden
//  sonrieras
//  sonrieran
//  divirtamos
//  deprimió
//  reconocieras
//  rieron
//  reconocieran
//  tarden
//  volvieras
//  volvieran
//  tardes
//  leído
//  enfado
//  enfade
//  puse
//  puso
//  supusimos
//  sacudo
//  metisteis
//  insistieron
//  recomendáis
//  pienso
//  dolemos
//  piensa
//  piense
//  mantendríamos
//  estimen
//  metiera
//  doláis
//  freías
//  satisficieran
//  alegréis
//  freían
//  suben
//  subes
//  resolvieran
//  evite
//  pruebo
//  ocurríamos
//  satisficieras
//  teñí
//  despidiéramos
//  salíamos
//  aprietan
//  influyo
//  apruebo
//  apruebe
//  aprueba
//  salí
//  sal
//  note
//  provoquemos
//  influyó
//  sale
//  cobre
//  cayerais
//  cobré
//  conversen
//  converses
//  desagradéis
//  prefirieras
//  duerman
//  veías
//  veían
//  duermas
//  moviera
//  cacéis
//  forméis
//  coloquemos
//  conviene
//  sugiriéramos
//  derritas
//  derritan
//  decidierais
//  fríen
//  despedido
//  midieran
//  midieras
//  charle
//  ayude
//  escondas
//  escondan
//  ilustréis
//  desaparecieras
//  comamos
//  pierden
//  llevéis
//  pierdes
//  asistes
//  asisten
//  acostumbréis
//  mereciéramos
//  proteja
//  protejo
//  sonriera
//  triunfes
//  hice
//  viera
//  inducían
//  inducías
//  solieran
//  solieras
//  influyes
//  huyera
//  sugiriendo
//  salte
//  destruíamos
//  establezcáis
//  digan
//  sucedas
//  digas
//  opongas
//  opongan
//  veníamos
//  derritieran
//  respiré
//  naciéramos
//  atraviesen
//  atravieses
//  requiriéramos
//  deshicierais
//  ofrezcáis
//  pidieran
//  caliento
//  devuelvan
//  ejerzo
//  devuelvas
//  ejerza
//  movió
//  despedíais
//  vuelves
//  vuelven
//  caigamos
//  introduzcan
//  introduzcas
//  lea
//  ganéis
//  reduciendo
//  celebre
//  debáis
//  hería
//  pierdas
//  contuvieran
//  celebremos
//  contuvieras
//  calcule
//  reciba
//  recibo
//  tiñera
//  emborrachemos
//  celebré
//  caigo
//  fingiendo
//  unte
//  escojan
//  consiguieron
//  oyeras
//  oyeran
//  elegían
//  elegías
//  compusieran
//  creáis
//  compusieras
//  finja
//  consumen
//  cogiera
//  vistáis
//  satisfaría
//  prohibamos
//  consumes
//  mantenemos
//  derritieras
//  despiden
//  despides
//  cubríamos
//  haremos
//  reciban
//  recibas
//  coséis
//  sucedía
//  pidiéramos
//  prometamos
//  sacudían
//  sacudías
//  pidieron
//  traduzcamos
//  despidiendo
//  renació
//  salven
//  conservéis
//  salves
//  mantuvimos
//  convirtáis
//  fuerais
//  uní
//  convido
//  convide
//  temiste
//  sintierais
//  contuvierais
//  aprendan
//  rompáis
//  lavéis
//  expusimos
//  vayas
//  vayan
//  requirió
//  divirtáis
//  expuesto
//  una
//  nade
//  prometisteis
//  emborrachéis
//  cabría
//  prosiguiéramos
//  muerto
//  distinguieron
//  compremos
//  partamos
//  rijan
//  predigas
//  predigan
//  rijas
//  votes
//  recojas
//  voten
//  paréis
//  eligió
//  derritió
//  constituíamos
//  ahorre
//  recen
//  reces
//  ahorré
//  doblen
//  dobles
//  ofendiéramos
//  compongan
//  cumplido
//  querréis
//  invirtieran
//  acompañe
//  invirtieras
//  descienden
//  invertíamos
//  opondré
//  admita
//  admito
//  reducimos
//  ocurrió
//  insistíamos
//  despedimos
//  beba
//  bebo
//  abriendo
//  comió
//  perteneciéramos
//  abracen
//  preparéis
//  aprendamos
//  venda
//  permitas
//  partiendo
//  permitan
//  compitieran
//  requeríais
//  resuelvan
//  resuelvas
//  levanten
//  eligieran
//  eligieras
//  gruñíamos
//  salió
//  muevan
//  muevas
//  pondré
//  trabaje
//  lleve
//  conserves
//  conserven
//  haríamos
//  reduzco
//  construyera
//  bauticemos
//  corregían
//  haríais
//  propusieran
//  propusieras
//  continúe
//  continúa
//  continúo
//  desagrade
//  riñeran
//  presintéramos
//  acuesten
//  acuestes
//  vomiten
//  vomites
//  producían
//  preveamos
//  herví
//  querrían
//  querrías
//  derretíamos
//  persigas
//  doliéramos
//  persigan
//  avancemos
//  supusiste
//  predecimos
//  previéramos
//  lancemos
//  disminuyeran
//  disminuyeras
//  sufrido
//  venciéramos
//  cuido
//  cuide
//  proponemos
//  aburría
//  distribuyó
//  subí
//  distribuyo
//  sonriamos
//  sugirierais
//  aconteciéramos
//  vistiéramos
//  valió
//  vuelvas
//  vendrá
//  inducíamos
//  construyeron
//  amanecieras
//  tropecemos
//  amanecieran
//  hable
//  caces
//  cacen
//  abras
//  abran
//  manejen
//  manejes
//  engañes
//  engañen
//  entremos
//  cogiste
//  conduzcáis
//  brinde
//  rechace
//  volviste
//  mudéis
//  invadisteis
//  sintió
//  consintieran
//  torzáis
//  desarrollen
//  desarrolles
//  decidisteis
//  prefieras
//  ocurras
//  heredéis
//  ocurran
//  prefiera
//  apruebes
//  comas
//  aprueben
//  coman
//  tendré
//  expondré
//  efectúen
//  ido
//  trate
//  disminuíamos
//  dude
//  deshice
//  necesite
//  comprenda
//  comprendo
//  introducimos
//  descubrieron
//  preferido
//  riñamos
//  hieras
//  hieran
//  tañó
//  pagues
//  paguen
//  reduzcan
//  reduzcas
//  alientan
//  taña
//  alientas
//  emigre
//  pudiera
//  siguiendo
//  bendito
//  vuelto
//  confieses
//  pudiéramos
//  confiesen
//  cogimos
//  graduéis
//  niego
//  expondrías
//  lancen
//  lances
//  expondrían
//  contuviéramos
//  divierto
//  quería
//  robemos
//  regido
//  dormían
//  emigréis
//  exhibo
//  exhiba
//  contendrías
//  anduve
//  anduvo
//  comience
//  contendrían
//  contendríamos
//  despierte
//  despierto
//  tiñendo
//  distribuyera
//  gradúas
//  suspiréis
//  participes
//  enferméis
//  describas
//  describan
//  midiéramos
//  cobréis
//  participen
//  rigiéramos
//  afeite
//  prosigue
//  barriste
//  enfermes
//  enfermen
//  incluyeras
//  incluyeran
//  mantén
//  protegisteis
//  reíamos
//  calculen
//  calcules
//  mienta
//  miente
//  miento
//  huyes
//  huyen
//  saldríamos
//  alcancen
//  alcances
//  presente
//  recomendéis
//  supieras
//  expusieron
//  supieran
//  tapes
//  recojan
//  tapen
//  vendiéramos
//  erais
//  tañáis
//  visteis
//  sufrías
//  asistamos
//  torció
//  sufrían
//  convendrán
//  repitiera
//  convendrás
//  requerías
//  requerían
//  despidieron
//  muere
//  muera
//  oído
//  muero
//  decoréis
//  escojas
//  resolvierais
//  presintierais
//  quise
//  quiso
//  rigierais
//  ahorréis
//  abrió
//  sufrieron
//  gruñías
//  gruñían
//  añadieron
//  divirtiéramos
//  devolvisteis
//  aburras
//  prosiguieran
//  hervías
//  hervían
//  aburran
//  prosiguieras
//  surjo
//  surja
//  pueden
//  queramos
//  produzcan
//  produzcas
//  dolisteis
//  satiricemos
//  encienden
//  oyerais
//  enciendes
//  aumente
//  vinimos
//  atiendo
//  consintiéramos
//  esperéis
//  consienten
//  quedéis
//  acordéis
//  sigáis
//  consientes
//  corrijáis
//  bendigamos
//  lloviéramos
//  erré
//  enflaquecieran
//  enflaquecieras
//  toso
//  tosa
//  tarde
//  vista
//  viste
//  visto
//  moría
//  olierais
//  yaciéramos
//  abordéis
//  escribáis
//  dio
//  invierto
//  satisfaríamos
//  reñía
//  unieron
//  previó
//  permito
//  surgido
//  hervido
//  riñáis
//  consumíais
//  predice
//  lloremos
//  cabrá
//  sugirieran
//  cabré
//  convirtieran
//  creísteis
//  convirtieras
//  venido
//  sientes
//  ría
//  ríe
//  sienten
//  río
//  corramos
//  entretengan
//  entretengas
//  creíste
//  vinierais
//  metía
//  sean
//  recomiende
//  recomienda
//  recomiendo
//  compusierais
//  preveáis
//  volviéramos
//  conseguí
//  distinguiendo
//  regulen
//  atrajeron
//  detén
//  guíen
//  guíes
//  hiciera
//  llueves
//  paran
//  paras
//  llueven
//  brindéis
//  vieras
//  vieran
//  pusieron
//  triunfemos
//  saldrá
//  distribuyes
//  tiñeras
//  tiñeran
//  deshicieron
//  volviera
//  culpéis
//  escogiéramos
//  aparezcáis
//  tuvimos
//  robéis
//  comiencen
//  comiences
//  corrigió
//  mintiéramos
//  propondrían
//  propondrías
//  lave
//  despidierais
//  renuevan
//  renuevas
//  toméis
//  rigen
//  riges
//  sepáis
//  gruñeras
//  gruñeran
//  cupe
//  corrijamos
//  gradúa
//  gradúe
//  gradúo
//  choquemos
//  ocurrí
//  vino
//  vine
//  castiguen
//  obtuviste
//  fingíamos
//  ocurro
//  ocurra
//  consuma
//  apuesto
//  apuesta
//  curéis
//  cumplieron
//  traducías
//  entré
//  huyó
//  traducían
//  consumí
//  estime
//  ríes
//  entre
//  huyo
//  solió
//  corrige
//  rijáis
//  encuentres
//  entusiasme
//  disminuyes
//  conduzcamos
//  disminuyen
//  influíamos
//  cubrían
//  llegues
//  lleguen
//  queméis
//  aburrió
//  reservemos
//  sonreíd
//  reciclen
//  recicles
//  cogisteis
//  pasen
//  sugerí
//  despedías
//  gruñas
//  repitiéramos
//  gruñan
//  cierro
//  exponemos
//  cierre
//  llovierais
//  anduvisteis
//  descanses
//  descansen
//  aplaudíamos
//  sustituyerais
//  mantendrías
//  pases
//  mantendrían
//  emborrachen
//  emborraches
//  mido
//  mide
//  mida
//  aprendiéramos
//  acostumbres
//  acostumbren
//  mostréis
//  eligiéramos
//  extingamos
//  persiguierais
//  murieron
//  sintáis
//  continuéis
//  aprenda
//  prefirió
//  copies
//  aprendo
//  copien
//  escojo
//  propón
//  reparemos
//  convirtiéramos
//  extiendo
//  opusieras
//  señale
//  opusieran
//  pusieran
//  volváis
//  pusieras
//  descubríamos
//  recordéis
//  quiero
//  quiere
//  quiera
//  destruyeras
//  llene
//  deprimamos
//  cuestas
//  entrevisten
//  entrevistes
//  cuestan
//  legalicemos
//  sacudiendo
//  solisteis
//  duré
//  convirtió
//  hierve
//  hierva
//  anduvierais
//  hiervo
//  dure
//  anduvieron
//  rehúsan
//  rehúsas
//  vuelan
//  vuelas
//  proseguíamos
//  inducimos
//  sufríamos
//  ayudéis
//  constituyerais
//  consigue
//  traigo
//  burle
//  diría
//  midas
//  suena
//  freí
//  suene
//  sueno
//  ruegue
//  asistiendo
//  convencieras
//  convencieran
//  derritiendo
//  cosiéramos
//  prosiguierais
//  sufriendo
//  rieguen
//  riegues
//  bendigas
//  acerquemos
//  sabíais
//  quemes
//  metan
//  reíais
//  metas
//  quemen
//  compren
//  opondrían
//  descanse
//  opondrías
//  dormía
//  descubráis
//  pedíamos
//  sugieran
//  censures
//  siguierais
//  censuren
//  luchéis
//  evacuemos
//  miréis
//  tendríamos
//  barríamos
//  oíste
//  enseñes
//  tosierais
//  detendré
//  suponemos
//  evites
//  eviten
//  cargues
//  tengan
//  vivo
//  supo
//  supe
//  tengas
//  atienden
//  atiendes
//  sintamos
//  fuiste
//  éramos
//  hirvieron
//  midan
//  hierven
//  evacuen
//  encontremos
//  evacues
//  convenzáis
//  recogierais
//  comieras
//  comieran
//  descubra
//  cojáis
//  descubre
//  descubro
//  imprimáis
//  perdones
//  perdonen
//  fingido
//  descubrí
//  caigan
//  prosigáis
//  agradecieras
//  agradecieran
//  respeten
//  decidamos
//  consumido
//  pruebe
//  cierran
//  prueba
//  cierras
//  oliste
//  mintamos
//  corrimos
//  merecieras
//  repites
//  merecieran
//  presintió
//  metemos
//  requieren
//  requieres
//  como
//  coma
//  sabríamos
//  deposites
//  depositen
//  repitamos
//  abría
//  mantengo
//  caliente
//  calienta
//  podríamos
//  obtuvieron
//  entretén
//  aprobéis
//  aprendas
//  reduzca
//  piensen
//  pienses
//  calle
//  mantuviste
//  propusiéramos
//  desciendes
//  advirtierais
//  temieran
//  importen
//  importes
//  vamos
//  bendigo
//  temiéramos
//  temieras
//  fueras
//  fueran
//  torciéramos
//  prometemos
//  actué
//  cumplo
//  sabrás
//  alegremos
//  repitieras
//  repitieran
//  seáis
//  introducido
//  consumieron
//  tuvieras
//  tuvieran
//  midió
//  supusisteis
//  ahorquemos
//  lamente
//  creído
//  entretuvisteis
//  inviertas
//  inviertan
//  perdáis
//  distingas
//  distingan
//  enriquezcáis
//  metió
//  bendecían
//  rio
//  bendecías
//  pesquemos
//  sufrió
//  durmiéramos
//  queme
//  persiguieron
//  respondemos
//  vinieron
//  predecías
//  predecían
//  queremos
//  desagrado
//  abráis
//  riñeras
//  invadíamos
//  distingamos
//  conduzco
//  lloviera
//  conduzca
//  salgamos
//  duermo
//  duerma
//  duerme
//  requiráis
//  calles
//  callen
//  cuento
//  cuente
//  cuenta
//  trajerais
//  tropiece
//  arroje
//  reducías
//  reducían
//  derritieron
//  eligiendo
//  matricules
//  hiriera
//  matriculen
//  notes
//  noten
//  salían
//  añadamos
//  salías
//  sonrieron
//  detengan
//  satisfaremos
//  detengas
//  esperemos
//  entretuviste
//  defiendan
//  defiendas
//  sugerían
//  cubría
//  sugerías
//  opuesto
//  invadierais
//  vistieras
//  muestran
//  muestras
//  seas
//  avancéis
//  estableciéramos
//  chismees
//  chismeen
//  grite
//  durmió
//  ejerzamos
//  confías
//  confían
//  ofreciéramos
//  distingáis
//  producías
//  vacío
//  vacíe
//  vacía
//  contribuyes
//  contribuyen
//  lloviste
//  oían
//  oías
//  sugiriera
//  violen
//  violes
//  compitió
//  valieran
//  mantengamos
//  valieras
//  hirvierais
//  ofrecieras
//  ofrecieran
//  persiguieran
//  persiguieras
//  prometieras
//  sacudáis
//  prometieran
//  combatiendo
//  agoremos
//  comencemos
//  friamos
//  surgí
//  lean
//  leas
//  preveíais
//  apaguen
//  apagues
//  surge
//  hereden
//  heredes
//  convinieron
//  cubras
//  alcance
//  cubran
//  desagradeciéramos
//  lance
//  avisen
//  avises
//  acampen
//  acampes
//  )
//  assert(i.toFloat/n > 0.80)
//}
//
////def("apply context test"){
////     assert(apply(tokensTags:List[(String,String)]))
////    }
//}